services:
  biami:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/Downloads/bin/test:/opt/biami/bin/temp
      - ~/Downloads/bin/env:/opt/biami/bin/env
      - ~/Downloads/bin/temp/db:/opt/biami/bin/db
    image: biami
    container_name: biami
    command: ["core_run.sh", "--context_param", "cmd=requestprocess", "--context_param", "taskid=7" ]