services:
  biami:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../test:/opt/biami/bin/temp
      - ../env:/opt/biami/bin/env
    image: biami
    container_name: biami